### ISSUE TITLE
Passing ['name'] string, not whole array to mail_exclusions() is wrong

### ISSUE THREAD

**Issue by TheLimey** [webforward/PHP-IMAP-Sync#1]
This hasn't been updated in four years, so you probably don't care, but I figured as it's out there it would be nice if it was working.

on Line 45 you pass only the 'name' array item value to the mail_exclusions function, but it is expecting the whole array.

Is this:
` if (mail_exclusions($s_folder['name'])) {`

...should be this:
`if (mail_exclusions($s_folder)) {`

I would submit a fix, but I don't use Github enough, and can't afford the time to work out how right now.

**Comment by mrl22** [comment]
Thank you once again, I have made the update in commit https://github.com/webforward/PHP-IMAP-Sync/blob/master/phpimapsync.php I have been using github and gist as a bit of a dumping ground for code I write in my job that I or others may find useful.
