### ISSUE TITLE
Folders created with leading dot in name

### ISSUE THREAD

**Issue by TheLimey** [webforward/PHP-IMAP-Sync#3]
When $t_prefix is not set to 'INBOX' the implode on line 58 causes the target folder name to have a leading dot.

I fixed this by adding the dot to the $t_prefix string, like this (Line 31):
`if (preg_match('/}INBOX/',$t_folders[0]['name'],$m)) $t_prefix = 'INBOX.';`

...and changing the implode to just a concatenate.
Was this:
`$t_folder = implode('.', array($t_prefix, $s_folder));`
Now this:
`$t_folder = "$t_prefix$s_folder";`

Now target folders get the correct names.

Next I need to add folder mappings so mail in "Sent Items" on source is copied to "Sent Mail" on target.

**Comment by mrl22** [comment]
Thank you, Sorry I only just saw this, have fixed in commit https://github.com/webforward/PHP-IMAP-Sync/commit/6775f59c72a1380301744a06ef931cab894752bb
